require 'rubygems'
require 'ffi-inliner'
require 'ffi-life/version'
require 'ffi-life/life'
require 'ffi-life/runners/runner'
require 'ffi-life/runners/console'
require 'ffi-life/runners/rubygame'
require 'ffi-life/application'
